require("Compatibilities.MetalStars_Vesta.Subgrupe")
require("Compatibilities.DiaDi.DiaDieHidingDisablingModContent")
require("Compatibilities.Linox.LinoxHidingDisablingModContent")
require("prototypes.Misc.VanillaHidingDisablingFunction")
require("Compatibilities.Bobs.BobRecipesFixes")