---@class Data.ItemPrototype
local Item = data.raw.item
---@class data.RecipePrototype
local Recipe = data.raw.recipe

if mods["boblogistics"]then
Recipe["roboport"].subgroupe = "Roboport"
Recipe["BRE-logistic-robotics-mk1"].order = "AA[robot]-AA[logistic-robot]"
Recipe["BRE-logistic-robotics-mk1"].subgroupe = "AA[robot]-AA[logistic-robot]"
Recipe["BRE-logistic-robotics-mk2"].order = "AA[robot]-AB[logistic-robot]"
Recipe["BRE-logistic-robotics-mk2"].subgroupe = "AA[robot]-AB[logistic-robot]"
Recipe["BRE-logistic-robotics-mk3"].order = "AA[robot]-AC[logistic-robot]"
Recipe["BRE-logistic-robotics-mk3"].subgroupe = "AA[robot]-AC[logistic-robot]"
Recipe["BRE-logistic-robotics-mk4"].order = "AA[robot]-AD[logistic-robot]"
Recipe["BRE-logistic-robotics-mk4"].subgroupe = "AA[robot]-AD[logistic-robot]"
Recipe["BRE-logistic-robotics-mk5"].order = "AA[robot]-AE[logistic-robot]"
Recipe["BRE-logistic-robotics-mk5"].subgroupe = "AA[robot]-AE[logistic-robot]"
Recipe["BRE-construction-robotics-mk1"].order = "AA[robot]-BA[construction-robot]"
Recipe["BRE-construction-robotics-mk1"].subgroupe = "AA[robot]-BA[construction-robot]"
Recipe["BRE-construction-robotics-mk2"].order = "AA[robot]-BB[construction-robot]"
Recipe["BRE-construction-robotics-mk2"].subgroupe = "AA[robot]-BB[construction-robot]"
Recipe["BRE-construction-robotics-mk3"].order = "AA[robot]-BC[construction-robot]"
Recipe["BRE-construction-robotics-mk3"].subgroupe = "AA[robot]-BC[construction-robot]"
Recipe["BRE-construction-robotics-mk4"].order = "AA[robot]-BD[construction-robot]"
Recipe["BRE-construction-robotics-mk4"].subgroupe = "AA[robot]-BD[construction-robot]"
Recipe["BRE-construction-robotics-mk5"].order = "AA[robot]-BE[construction-robot]"
Recipe["BRE-construction-robotics-mk5"].subgroupe = "AA[robot]-BE[construction-robot]"

Item["BRE-logistic-robotics-mk1"].order = "AA[robot]-AA[logistic-robot]"
Item["BRE-logistic-robotics-mk1"].subgroupe = "AA[robot]-AA[logistic-robot]"
Item["BRE-logistic-robotics-mk2"].order = "AA[robot]-AB[logistic-robot]"
Item["BRE-logistic-robotics-mk2"].subgroupe = "AA[robot]-AB[logistic-robot]"
Item["BRE-logistic-robotics-mk3"].order = "AA[robot]-AC[logistic-robot]"
Item["BRE-logistic-robotics-mk3"].subgroupe = "AA[robot]-AC[logistic-robot]"
Item["BRE-logistic-robotics-mk4"].order = "AA[robot]-AD[logistic-robot]"
Item["BRE-logistic-robotics-mk4"].subgroupe = "AA[robot]-AD[logistic-robot]"
Item["BRE-logistic-robotics-mk5"].order = "AA[robot]-AE[logistic-robot]"
Item["BRE-logistic-robotics-mk5"].subgroupe = "AA[robot]-AE[logistic-robot]"
Item["BRE-construction-robotics-mk1"].order = "AA[robot]-BA[construction-robot]"
Item["BRE-construction-robotics-mk1"].subgroupe = "AA[robot]-BA[construction-robot]"
Item["BRE-construction-robotics-mk2"].order = "AA[robot]-BB[construction-robot]"
Item["BRE-construction-robotics-mk2"].subgroupe = "AA[robot]-BB[construction-robot]"
Item["BRE-construction-robotics-mk3"].order = "AA[robot]-BC[construction-robot]"
Item["BRE-construction-robotics-mk3"].subgroupe = "AA[robot]-BC[construction-robot]"
Item["BRE-construction-robotics-mk4"].order = "AA[robot]-BD[construction-robot]"
Item["BRE-construction-robotics-mk4"].subgroupe = "AA[robot]-BD[construction-robot]"
Item["BRE-construction-robotics-mk5"].order = "AA[robot]-BE[construction-robot]"
Item["BRE-construction-robotics-mk5"].subgroupe = "AA[robot]-BE[construction-robot]"
end